### ISSUE TITLE
공지사항/이벤트 게시판 구현 - 조회

### ISSUE THREAD

**Issue by Javaiary** [Berry-G/YoungCultureCenter#12]
1. DB 생성 및 연결
2. 읽기, 수정 다른 페이지로 구현했던 것을 한 페이지에서 동작하도록 수정
3. 글 삭제하기 기능
4. 글 작성 권한 지정하기

**Comment by Berry-G** [comment]
![Image](https://user-images.githubusercontent.com/69233747/202419489-b222d1ed-d6c8-4f9b-82ea-8073c479c03e.png)

DB연결해서 값 조회하는 기능 구현
