### ISSUE TITLE
로그인 -> 로그아웃 버튼 SWAP

### ISSUE THREAD

**Issue by Javaiary** [Berry-G/YoungCultureCenter#15]
![Image](https://user-images.githubusercontent.com/69233747/201839392-53a95c43-58e9-40c9-ac97-15486556135f.png)

로그인 했을 시 드롭다운 메뉴로 마이페이지, 로그아웃, 나의수강목록, 1:1 문의 접근 가능하도록 구현

드롭다운 버튼에는 로그인한 USER_NAME 출력

**Comment by Berry-G** [comment]
USER_ID -> USER_NAME 으로 수정해주세요~

**Comment by Berry-G** [comment]
![Image](https://user-images.githubusercontent.com/69233747/202995438-cf8715dd-bde8-4e9a-89cb-b0bfc85202c9.png)

로그인 버튼 헤더 수정

**Comment by Berry-G** [comment]
### 로그인 했을 때 동작
![Image](https://user-images.githubusercontent.com/69233747/202995572-64640870-ec6d-45e3-a1ca-5748e5d5b9f9.png)




### 드롭다운 동작
![Image](https://user-images.githubusercontent.com/69233747/202995725-06e397e2-6ac5-4e37-bc69-f19e1aa13a5c.png)
