### ISSUE TITLE
자동 로그인 기능 구현

### ISSUE THREAD

**Issue by Berry-G** [Berry-G/YoungCultureCenter#17]
![Image](https://user-images.githubusercontent.com/69233747/201841283-05bfdbff-b230-4d69-95e1-1654f7d21308.png)

**Comment by Javaiary** [comment]
로직 참고

https://kdyspring.tistory.com/24

**Comment by Berry-G** [comment]
![image](https://user-images.githubusercontent.com/69233747/202993071-92b26c71-d907-4158-84ae-b81b7765bcde.png)

로직 플로우차트 참조

**Comment by Javaiary** [comment]
- 시큐리티에서 기본 제공하는 remember-me 기능 사용

jsp

![Image](https://user-images.githubusercontent.com/110982271/210206657-51006dbe-27cf-4f6b-9aa7-d1aff63c01b4.png)

security-context

![Image](https://user-images.githubusercontent.com/110982271/210206959-6b8dc308-47ce-41a0-a50c-c6fcfbc9a797.png)

60*60*24*30 : 기본 30일 설정

![Image](https://user-images.githubusercontent.com/110982271/210207535-1d5783f3-5306-4a98-bc9f-a7be40354b38.png)

자동로그인 체크(remember-me)시 persistent_logins 테이블에 저장
