### ISSUE TITLE
강좌검색페이지: DB 연결해서 리스트 불러오기

### ISSUE THREAD

**Issue by Berry-G** [Berry-G/YoungCultureCenter#23]
수강 테이블에서 DB의 내용물을 받아오고 내용물이 없으면 없다고 띄워주기.

**Comment by Berry-G** [comment]
![Image](https://user-images.githubusercontent.com/69233747/202395058-ea24af39-1152-4757-b8fe-affff570336c.png)

**Comment by xnlrlal** [comment]
![Image](https://user-images.githubusercontent.com/111483010/204071226-0d37c2e4-30ea-4b07-83d2-7d07ac93a0e6.png)

db에서 강의 리스트 출력
