### ISSUE TITLE
통합검색 결과 정렬기능 구현

### ISSUE THREAD

**Issue by Berry-G** [Berry-G/YoungCultureCenter#28]

**Comment by cyh6327** [comment]
## 1. 정확도순
- 디폴트값
![image](https://user-images.githubusercontent.com/99089584/216677424-ff604c38-c7fe-478a-964c-49391c1dd365.png)

## 2. 조회순
![image](https://user-images.githubusercontent.com/99089584/216677616-9656fae9-e306-4242-a6b4-999483e0d184.png)

## 3. 최신순
![image](https://user-images.githubusercontent.com/99089584/216677692-3d934275-b462-42b9-9ccd-c674fa70faa1.png)
