### ISSUE TITLE
대관:장소 선택 SELECT 박스에 DB값 불러오기

### ISSUE THREAD

**Issue by Berry-G** [Berry-G/YoungCultureCenter#35]

**Comment by alwaysFinn** [comment]
![image](https://user-images.githubusercontent.com/106485220/202628528-b998b95a-7725-4112-b1e7-ab8f8730ed5f.png)

DB불러올 시 공백 생기는 ISSUE 발생

**Comment by alwaysFinn** [comment]
![image](https://user-images.githubusercontent.com/106485220/202628897-d844805e-f500-47c7-bfe7-dd7a56b3b95b.png)

공백 ISSUE 해결
