### ISSUE TITLE
사물함 : 사물함 DB에서 값 불러오기

### ISSUE THREAD

**Issue by Berry-G** [Berry-G/YoungCultureCenter#37]
1. DB에서 체크 여부 값 불러와서 체크가능 여부 반영하고
2. 사물함 위치별로 불러오는 DB 컬럼 변경해주는 기능 구현

**Comment by xnlrlal** [comment]
1. DB에서 예약현황 SELECT해오기

![Image](https://user-images.githubusercontent.com/111483010/209527172-b670158d-4288-44da-9bf5-df38ab9e7053.png)

2. 장소별로 사물함 예약현황 SELECT

![Image](https://user-images.githubusercontent.com/111483010/209527289-cebf28d8-1b90-4c62-9862-91d496876644.png)

**Comment by xnlrlal** [comment]
GET방식으로 장소별 location_id 쿼리스트링으로 출력 

![Image](https://user-images.githubusercontent.com/111483010/209527430-42f22f73-cb98-417d-9fe1-2ea9fd989ae2.png)

![Image](https://user-images.githubusercontent.com/111483010/209527465-50a6588f-52fc-449e-b21f-9ac8b02132cc.png)
