### ISSUE TITLE
대관장소 불러오기

### ISSUE THREAD

**Issue by Berry-G** [Berry-G/YoungCultureCenter#39]

**Comment by cyh6327** [comment]
## 장소 목록 db값 출력
![image](https://user-images.githubusercontent.com/99089584/216679225-2df0a0eb-14a8-4dfd-9853-de3dff806dd2.png)

## 장소, 날짜 선택 후 조회하기
![image](https://user-images.githubusercontent.com/99089584/216679406-1d65ea56-2ac5-494d-9844-167e65b153e7.png)
