### ISSUE TITLE
체크박스 선택 된 대여장소 한꺼번에 결제 하는 로직 구현

### ISSUE THREAD

**Issue by Berry-G** [Berry-G/YoungCultureCenter#40]

**Comment by cyh6327** [comment]
## 시간대 다중 선택
![image](https://user-images.githubusercontent.com/99089584/216679572-1fc0359c-b0f8-4bd0-ab13-9258fb098ba7.png)

## 모달창에 선택한 시간대 모두 출력
![image](https://user-images.githubusercontent.com/99089584/216679801-04814422-7714-485e-bef8-6b8c991dfde6.png)

## 정상적으로 예약 처리됨
![image](https://user-images.githubusercontent.com/99089584/216679943-58af782c-562f-4a3f-923b-af0999c643b3.png)
