### ISSUE TITLE
독서실:체크 된 좌석 내용 모달창으로 전송

### ISSUE THREAD

**Issue by Berry-G** [Berry-G/YoungCultureCenter#42]
1. 선택한 좌석 모달창으로 전달
2. 결제 페이지로 넘길 때 입실예정시간 + 이용시간 합쳐서 표시

**Comment by alwaysFinn** [comment]
![Image](https://user-images.githubusercontent.com/106485220/206510406-924f2d08-828e-41bf-bfbf-3e6a27c48b5f.png)



![Image](https://user-images.githubusercontent.com/106485220/206510833-8977889d-d80d-4473-b04b-b02177fb602f.png)



선택된 selectbox가 <c:forEach>로 출력시 선택되지 않는 issue

**Comment by alwaysFinn** [comment]
![Image](https://user-images.githubusercontent.com/106485220/206512086-230ef818-02eb-4a7e-94c9-278c4e3b5386.png)

하드코딩으로 insert문 테스트 중 issue

**Comment by alwaysFinn** [comment]
![Image](https://user-images.githubusercontent.com/106485220/206659355-802f4b61-5d0f-4139-a64b-66c63c970be3.png)

insert시 종료 시간을 제대로 받아가다가 db에는 00:00:00으로 입력되는 issue

**Comment by alwaysFinn** [comment]
![Image](https://user-images.githubusercontent.com/106485220/206659721-1f54e880-50fd-4876-a90e-29d205db25ea.png)

mapper에서 ::date를 제거하니 해결

**Comment by alwaysFinn** [comment]
![Image](https://user-images.githubusercontent.com/106485220/207865545-bff3e44d-a80b-4cbd-915c-e5427f900251.png)

- 반복문으로 1~46까지의 좌석 출력, value에 좌석 id를 넣어서 해당 radio 선택 시 값이 담기게 설정

![Image](https://user-images.githubusercontent.com/106485220/207865781-8b2dd552-659f-4848-9268-a9911322f506.png)

- 모달창에서 보여줄 부분에 id를 지정

![Image](https://user-images.githubusercontent.com/106485220/207866285-1fbdb0ee-d6db-42cd-afb8-790f445c1184.png)

- 앞서 지정한 id를 기반으로 위치를 찾아 innerHTML로 값을 넘겨줌
