### ISSUE TITLE
독서실:좌석 정보 DB에서 받아와서 enable/disable 뿌려주기

### ISSUE THREAD

**Issue by Berry-G** [Berry-G/YoungCultureCenter#43]

**Comment by alwaysFinn** [comment]
![Image](https://user-images.githubusercontent.com/106485220/207848850-15334e4b-739b-4635-bfbb-abdac5af1da7.png)

value의 값을 기준으로
y일 경우 : 예약된 좌석
n일 경우 : 빈 좌석



![Image](https://user-images.githubusercontent.com/106485220/207849084-47d219e7-b51f-4edc-8e49-956323c9ec5b.png)
