### ISSUE TITLE
강좌검색페이지: 분류 검색 폼에서 초기화버튼 구현

### ISSUE THREAD

**Issue by Berry-G** [Berry-G/YoungCultureCenter#46]

**Comment by xnlrlal** [comment]
![Image](https://user-images.githubusercontent.com/111483010/204072889-a095f5f6-225e-42f3-8eb0-b6da039604af.png)



![Image](https://user-images.githubusercontent.com/111483010/204073004-00dc3c10-c153-4049-8462-5dc7e1499c3e.png)

초기화 버튼 누르면 드롭다운 & 검색창 초기화
