### ISSUE TITLE
강좌상세페이지: DB연결하기

### ISSUE THREAD

**Issue by Berry-G** [Berry-G/YoungCultureCenter#47]

**Comment by xnlrlal** [comment]
![Image](https://user-images.githubusercontent.com/111483010/204073431-f33bd71d-77fa-4b02-b723-72cb82b07c72.png)


![Image](https://user-images.githubusercontent.com/111483010/204073459-4bb2acaa-2513-4e29-b519-2b52805ec9c9.png)



db 연결해서 불러오기
