### ISSUE TITLE
관리자페이지 : 이용약관 관리

### ISSUE THREAD

**Issue by Berry-G** [Berry-G/YoungCultureCenter#51]
![Image](https://user-images.githubusercontent.com/69233747/202418066-c08114fb-3e1e-4af3-8cc6-0e6d90f9aba1.png)

**Comment by alwaysFinn** [comment]
DB에서 값을 불러올 때 사진처럼 공백과 함께 오는 issue 발생


![Image](https://user-images.githubusercontent.com/106485220/205481066-1ce87127-16ec-4dc1-9500-7d90f755f3e4.png)

**Comment by alwaysFinn** [comment]
textarea안에 공백(띄어쓰기, enter)이 들어있어 발생했던 ISSUE, 해결 완료


![Image](https://user-images.githubusercontent.com/106485220/205481268-03acf2a0-159a-4387-808f-df956c1828ba.png)

**Comment by alwaysFinn** [comment]
![Image](https://user-images.githubusercontent.com/106485220/205853163-49874bad-4a2e-4c97-8a00-a6beb401ce53.png)



![Image](https://user-images.githubusercontent.com/106485220/205853244-c91fa55c-9e2b-47e7-9928-0a105c8f7fa4.png)



1. 어드민 페이지에서 약관 수정 후 저장
2. 회원가입 양식에서 보여짐
